ProtocolConfiguration:
  Magic: 56753
  AddressVersion: 23
  SecondsPerBlock: 15
  LowPriorityThreshold: 0.000
  MemPoolSize: 50000
  StandbyValidators:
    - 02b3622bf4017bdfe317c58aed5f4c753f206b7db896046fa7d774bbc4bf7f8dc2
    - 02103a7f7dd016558597f7960d27c516a4394fd968b9e65155eb4b013e4040406e
    - 03d90c07df63e690ce77912e10ab51acc944b66860237b608c4f8f8309e71ee699
    - 02a7bc55fe8684e0119768d104ba30795bdcc86619e864add26156723ed185cd62
  SeedList:
    - 15.0.0.2:20333
    - 15.0.0.3:20334
    - 15.0.0.4:20335
    - 15.0.0.5:20336
  SystemFee:
    EnrollmentTransaction: 1000
    IssueTransaction: 500
    PublishTransaction: 500
    RegisterTransaction: 10000
  VerifyBlocks: true
  VerifyTransactions: true

ApplicationConfiguration:
  DBConfiguration:
    Type: "leveldb"
    LevelDBOptions:
      DataDirectoryPath: "/chains/one"
  NodePort: 20333
  Relay: true
  DialTimeout: 3
  ProtoTickInterval: 2
  PingInterval: 30
  PingTimeout: 90
  MaxPeers: 10
  AttemptConnPeers: 5
  MinPeers: 3
  RPC:
    Enabled: true
    EnableCORSWorkaround: false
    Port: 30333
  Prometheus:
    Enabled: true
    Port: 20001
  Pprof:
    Enabled: false
    Port: 20011
  UnlockWallet:
    Path: "/wallet1.json"
    Password: "one"
